services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SA_PASSWORD=Mitsuru12345!
    networks:
      - fleet
    ports:
      - 8090:8090
    depends_on:
      - db

  db:
    container_name: database
    build:
      context: .
      dockerfile: Dockerfile.db
    networks:
      - fleet
    ports:
      - 1433:1433
    volumes:
      - /c/db_backup/LocationTracker.bak:/var/opt/mssql/backup/LocationTracker.bak
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Mitsuru12345!

networks:
  fleet:

volumes:
  sqlvolume:  
